version: 2.1
orbs:
  node: circleci/node@3.0.1
jobs:
  build-and-lint:
    executor:
      name: node/default
    steps:
      - checkout
      - run: yarn
      - run: yarn lint
workflows:
  build-and-lint:
    jobs:
      - build-and-lint
